// <auto-generated />
using System;
using DesktopDiplomProject.Server.Data.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DesktopDiplomProject.Database.Migrations
{
    [DbContext(typeof(UpgradePCApplicationContext))]
    [Migration("20260414171429_FourthMigration")]
    partial class FourthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DesktopDiplomProject.Database.Models.Entities.Authentification.RefreshTokenEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIP")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JWTID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReplacedByTokenID")
                        .HasColumnType("integer");

                    b.Property<int?>("ReplacedByTokenOfID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIP")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedByIP")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ReplacedByTokenID")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID", "IsRevoked", "ExpiryDate");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Authentification.RoleEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Authentification.UserEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUBaseFrequencyEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("CPUBaseFrequencies");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUCoreCountEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("CPUCoreCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<int>("BaseFrequencyID")
                        .HasColumnType("integer");

                    b.Property<int>("CountCoresID")
                        .HasColumnType("integer");

                    b.Property<int>("CountThreadsID")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceID")
                        .HasColumnType("integer");

                    b.Property<int>("RAMTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("SocketID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BaseFrequencyID");

                    b.HasIndex("CountCoresID");

                    b.HasIndex("CountThreadsID");

                    b.HasIndex("PriceID");

                    b.HasIndex("RAMTypeID");

                    b.HasIndex("SocketID");

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUPriceEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("CPUPrices");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUSocketEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sockets");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUThreadsCountEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("CPUThreadsCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveCapacityEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("DriveCapacities");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveConnectionInterfaceEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DriveConnectionInterfaces");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<int>("CapacityID")
                        .HasColumnType("integer");

                    b.Property<int>("ConnectorInterfaceID")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceID")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedDataTransferID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CapacityID");

                    b.HasIndex("ConnectorInterfaceID");

                    b.HasIndex("PriceID");

                    b.HasIndex("SpeedDataTransferID");

                    b.ToTable("Drives");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DrivePriceEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("DrivePrices");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveSpeedDataTransferEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("DriveDataTransferSpeeds");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountM2SlotsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MBCountM2Slots");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountPCIEX16SlotsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MBCountPCIEX16Slots");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountSATASlotsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MBCountSATASlots");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBPriceEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("MBPrices");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMCountSlotsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MBRAMSlotsCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMFrequencyEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MBRAMFrequecies");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMValueEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MBRAMValues");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBSizeEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MBSizes");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MotherboardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<int>("CountM2SlotsID")
                        .HasColumnType("integer");

                    b.Property<int>("CountPCIEX16SlotsID")
                        .HasColumnType("integer");

                    b.Property<int>("CountSATASlotsID")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxRAMFrequencyID")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRAMValueID")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PCIEInterfaceID")
                        .HasColumnType("integer");

                    b.Property<int>("PriceID")
                        .HasColumnType("integer");

                    b.Property<int>("RAMCountSlotsID")
                        .HasColumnType("integer");

                    b.Property<int>("RAMTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("SizeID")
                        .HasColumnType("integer");

                    b.Property<int>("SocketID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CountM2SlotsID");

                    b.HasIndex("CountPCIEX16SlotsID");

                    b.HasIndex("CountSATASlotsID");

                    b.HasIndex("MaxRAMFrequencyID");

                    b.HasIndex("MaxRAMValueID");

                    b.HasIndex("PCIEInterfaceID");

                    b.HasIndex("PriceID");

                    b.HasIndex("RAMCountSlotsID");

                    b.HasIndex("RAMTypeID");

                    b.HasIndex("SizeID");

                    b.HasIndex("SocketID");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMCountModulesEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("RAMModulesCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<int>("CountModulesID")
                        .HasColumnType("integer");

                    b.Property<int>("FrequencyID")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceID")
                        .HasColumnType("integer");

                    b.Property<int>("RAMTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("SingleModuleCapacityID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CountModulesID");

                    b.HasIndex("FrequencyID");

                    b.HasIndex("PriceID");

                    b.HasIndex("RAMTypeID");

                    b.HasIndex("SingleModuleCapacityID");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMFrequencyEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("RAMFrequencies");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMPriceEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("RAMPrices");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMSingleModuleCapacityEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("RAMSingleModuleCapacities");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMTypeEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RAMTypes");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountRTCoresEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GPURTCoresCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountRasterizationBlocksEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GPURasterizationBlocksCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountTensorCoresEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GPUTensorCoresCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountTexturerBlocksEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GPUTexturesBlocksCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountUniversalProcessorsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GPUUniversalProcessorsCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<int>("BaseFrequencyID")
                        .HasColumnType("integer");

                    b.Property<int>("CountRTCoresID")
                        .HasColumnType("integer");

                    b.Property<int>("CountRasterizationBlocksID")
                        .HasColumnType("integer");

                    b.Property<int>("CountTensorCoresID")
                        .HasColumnType("integer");

                    b.Property<int>("CountTexturerBlocksID")
                        .HasColumnType("integer");

                    b.Property<int>("CountUniversalProcessorsID")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BaseFrequencyID");

                    b.HasIndex("CountRTCoresID");

                    b.HasIndex("CountRasterizationBlocksID");

                    b.HasIndex("CountTensorCoresID");

                    b.HasIndex("CountTexturerBlocksID");

                    b.HasIndex("CountUniversalProcessorsID");

                    b.ToTable("GPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUFrequencyEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GPUFrequencies");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.PCIEInterfaceEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PCIEInterfaces");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCCapacityVideoMemoryEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("VCVideoMemoryCapacities");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCCountMonitorsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("VCMonitorsCounties");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCMemoryFrequencyEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("VCMemoryFrequencies");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCPriceEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("VCPrices");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCThroughputCapacityEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<double>("ScoreFive")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreFour")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreOne")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreThree")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreTwo")
                        .HasColumnType("double precision");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("VCThroughputCapacities");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VideoCardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<int>("CapacityVideoMemoryID")
                        .HasColumnType("integer");

                    b.Property<int>("CountMonitorsID")
                        .HasColumnType("integer");

                    b.Property<int>("CountPCIELines")
                        .HasColumnType("integer");

                    b.Property<int>("CountPinsAdditionalPower")
                        .HasColumnType("integer");

                    b.Property<int>("GPUID")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxThroughputCapacityID")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryFrequencyID")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PCIEInterfaceID")
                        .HasColumnType("integer");

                    b.Property<int>("PriceID")
                        .HasColumnType("integer");

                    b.Property<int>("RecommendedBlockPower")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CapacityVideoMemoryID");

                    b.HasIndex("CountMonitorsID");

                    b.HasIndex("GPUID");

                    b.HasIndex("MaxThroughputCapacityID");

                    b.HasIndex("MemoryFrequencyID");

                    b.HasIndex("PCIEInterfaceID");

                    b.HasIndex("PriceID");

                    b.ToTable("VideoCards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.PersonalComputers.PCEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ID"));

                    b.Property<int>("CPUID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DriveID")
                        .HasColumnType("integer");

                    b.Property<int>("MotherboardID")
                        .HasColumnType("integer");

                    b.Property<int>("RAMID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("VideoCardID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CPUID");

                    b.HasIndex("DriveID");

                    b.HasIndex("MotherboardID");

                    b.HasIndex("RAMID");

                    b.HasIndex("UserID");

                    b.HasIndex("VideoCardID");

                    b.ToTable("PCs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Database.Models.Entities.Authentification.RefreshTokenEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Database.Models.Entities.Authentification.RefreshTokenEntity", "ReplacedByToken")
                        .WithOne("ReplacedByTokenOf")
                        .HasForeignKey("DesktopDiplomProject.Database.Models.Entities.Authentification.RefreshTokenEntity", "ReplacedByTokenID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Authentification.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Authentification.UserEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Authentification.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUBaseFrequencyEntity", "BaseFrequency")
                        .WithMany("CPUs")
                        .HasForeignKey("BaseFrequencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUCoreCountEntity", "CountCores")
                        .WithMany("CPUs")
                        .HasForeignKey("CountCoresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUThreadsCountEntity", "CountThreads")
                        .WithMany("CPUs")
                        .HasForeignKey("CountThreadsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUPriceEntity", "Price")
                        .WithMany("CPUs")
                        .HasForeignKey("PriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMTypeEntity", "RAMType")
                        .WithMany("CPUs")
                        .HasForeignKey("RAMTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUSocketEntity", "Socket")
                        .WithMany("CPUs")
                        .HasForeignKey("SocketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseFrequency");

                    b.Navigation("CountCores");

                    b.Navigation("CountThreads");

                    b.Navigation("Price");

                    b.Navigation("RAMType");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveCapacityEntity", "Capacity")
                        .WithMany("Drives")
                        .HasForeignKey("CapacityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveConnectionInterfaceEntity", "ConnectorInterface")
                        .WithMany("Drives")
                        .HasForeignKey("ConnectorInterfaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DrivePriceEntity", "Price")
                        .WithMany("Drives")
                        .HasForeignKey("PriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveSpeedDataTransferEntity", "SpeedDataTransfer")
                        .WithMany("Drives")
                        .HasForeignKey("SpeedDataTransferID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacity");

                    b.Navigation("ConnectorInterface");

                    b.Navigation("Price");

                    b.Navigation("SpeedDataTransfer");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MotherboardEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountM2SlotsEntity", "CountM2Slots")
                        .WithMany("Motherboards")
                        .HasForeignKey("CountM2SlotsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountPCIEX16SlotsEntity", "CountPCIEX16Slots")
                        .WithMany("Motherboards")
                        .HasForeignKey("CountPCIEX16SlotsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountSATASlotsEntity", "CountSATASlots")
                        .WithMany("Motherboards")
                        .HasForeignKey("CountSATASlotsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMFrequencyEntity", "MaxRAMFrequency")
                        .WithMany("Motherboards")
                        .HasForeignKey("MaxRAMFrequencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMValueEntity", "MaxRAMValue")
                        .WithMany("Motherboards")
                        .HasForeignKey("MaxRAMValueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.PCIEInterfaceEntity", "PCIEInterface")
                        .WithMany("Motherboards")
                        .HasForeignKey("PCIEInterfaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBPriceEntity", "Price")
                        .WithMany("Motherboards")
                        .HasForeignKey("PriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMCountSlotsEntity", "RAMCountSlots")
                        .WithMany("Motherboards")
                        .HasForeignKey("RAMCountSlotsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMTypeEntity", "RAMType")
                        .WithMany("Motherboards")
                        .HasForeignKey("RAMTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBSizeEntity", "Size")
                        .WithMany("Motherboards")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUSocketEntity", "Socket")
                        .WithMany("Motherboards")
                        .HasForeignKey("SocketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountM2Slots");

                    b.Navigation("CountPCIEX16Slots");

                    b.Navigation("CountSATASlots");

                    b.Navigation("MaxRAMFrequency");

                    b.Navigation("MaxRAMValue");

                    b.Navigation("PCIEInterface");

                    b.Navigation("Price");

                    b.Navigation("RAMCountSlots");

                    b.Navigation("RAMType");

                    b.Navigation("Size");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMCountModulesEntity", "CountModules")
                        .WithMany("RAMs")
                        .HasForeignKey("CountModulesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMFrequencyEntity", "Frequency")
                        .WithMany("RAMs")
                        .HasForeignKey("FrequencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMPriceEntity", "Price")
                        .WithMany("RAMs")
                        .HasForeignKey("PriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMTypeEntity", "RAMType")
                        .WithMany("RAMs")
                        .HasForeignKey("RAMTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMSingleModuleCapacityEntity", "SingleModuleCapacity")
                        .WithMany("RAMs")
                        .HasForeignKey("SingleModuleCapacityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountModules");

                    b.Navigation("Frequency");

                    b.Navigation("Price");

                    b.Navigation("RAMType");

                    b.Navigation("SingleModuleCapacity");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUFrequencyEntity", "BaseFrequency")
                        .WithMany("GPUs")
                        .HasForeignKey("BaseFrequencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountRTCoresEntity", "CountRTCores")
                        .WithMany("GPUs")
                        .HasForeignKey("CountRTCoresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountRasterizationBlocksEntity", "CountRasterizationBlocks")
                        .WithMany("GPUs")
                        .HasForeignKey("CountRasterizationBlocksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountTensorCoresEntity", "CountTensorCores")
                        .WithMany("GPUs")
                        .HasForeignKey("CountTensorCoresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountTexturerBlocksEntity", "CountTexturerBlocks")
                        .WithMany("GPUs")
                        .HasForeignKey("CountTexturerBlocksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountUniversalProcessorsEntity", "CountUniversalProcessors")
                        .WithMany("GPUs")
                        .HasForeignKey("CountUniversalProcessorsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseFrequency");

                    b.Navigation("CountRTCores");

                    b.Navigation("CountRasterizationBlocks");

                    b.Navigation("CountTensorCores");

                    b.Navigation("CountTexturerBlocks");

                    b.Navigation("CountUniversalProcessors");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VideoCardEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCCapacityVideoMemoryEntity", "CapacityVideoMemory")
                        .WithMany("VideoCards")
                        .HasForeignKey("CapacityVideoMemoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCCountMonitorsEntity", "CountMonitors")
                        .WithMany("VideoCards")
                        .HasForeignKey("CountMonitorsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUEntity", "GPU")
                        .WithMany("VideoCards")
                        .HasForeignKey("GPUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCThroughputCapacityEntity", "MaxThroughputCapacity")
                        .WithMany("VideoCards")
                        .HasForeignKey("MaxThroughputCapacityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCMemoryFrequencyEntity", "MemoryFrequency")
                        .WithMany("VideoCards")
                        .HasForeignKey("MemoryFrequencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.PCIEInterfaceEntity", "PCIEInterface")
                        .WithMany("VideoCards")
                        .HasForeignKey("PCIEInterfaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCPriceEntity", "Price")
                        .WithMany("VideoCards")
                        .HasForeignKey("PriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapacityVideoMemory");

                    b.Navigation("CountMonitors");

                    b.Navigation("GPU");

                    b.Navigation("MaxThroughputCapacity");

                    b.Navigation("MemoryFrequency");

                    b.Navigation("PCIEInterface");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.PersonalComputers.PCEntity", b =>
                {
                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUEntity", "CPU")
                        .WithMany("PCs")
                        .HasForeignKey("CPUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveEntity", "Drive")
                        .WithMany("PCs")
                        .HasForeignKey("DriveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MotherboardEntity", "Motherboard")
                        .WithMany("PCs")
                        .HasForeignKey("MotherboardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMEntity", "RAM")
                        .WithMany("PCs")
                        .HasForeignKey("RAMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Authentification.UserEntity", "User")
                        .WithMany("PCs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VideoCardEntity", "VideoCard")
                        .WithMany("PCs")
                        .HasForeignKey("VideoCardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CPU");

                    b.Navigation("Drive");

                    b.Navigation("Motherboard");

                    b.Navigation("RAM");

                    b.Navigation("User");

                    b.Navigation("VideoCard");
                });

            modelBuilder.Entity("DesktopDiplomProject.Database.Models.Entities.Authentification.RefreshTokenEntity", b =>
                {
                    b.Navigation("ReplacedByTokenOf");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Authentification.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Authentification.UserEntity", b =>
                {
                    b.Navigation("PCs");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUBaseFrequencyEntity", b =>
                {
                    b.Navigation("CPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUCoreCountEntity", b =>
                {
                    b.Navigation("CPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUEntity", b =>
                {
                    b.Navigation("PCs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUPriceEntity", b =>
                {
                    b.Navigation("CPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUSocketEntity", b =>
                {
                    b.Navigation("CPUs");

                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.CPUs.CPUThreadsCountEntity", b =>
                {
                    b.Navigation("CPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveCapacityEntity", b =>
                {
                    b.Navigation("Drives");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveConnectionInterfaceEntity", b =>
                {
                    b.Navigation("Drives");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveEntity", b =>
                {
                    b.Navigation("PCs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DrivePriceEntity", b =>
                {
                    b.Navigation("Drives");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Drives.DriveSpeedDataTransferEntity", b =>
                {
                    b.Navigation("Drives");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountM2SlotsEntity", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountPCIEX16SlotsEntity", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBCountSATASlotsEntity", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBPriceEntity", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMCountSlotsEntity", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMFrequencyEntity", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBRAMValueEntity", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MBSizeEntity", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.Motherboards.MotherboardEntity", b =>
                {
                    b.Navigation("PCs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMCountModulesEntity", b =>
                {
                    b.Navigation("RAMs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMEntity", b =>
                {
                    b.Navigation("PCs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMFrequencyEntity", b =>
                {
                    b.Navigation("RAMs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMPriceEntity", b =>
                {
                    b.Navigation("RAMs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMSingleModuleCapacityEntity", b =>
                {
                    b.Navigation("RAMs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.RAMs.RAMTypeEntity", b =>
                {
                    b.Navigation("CPUs");

                    b.Navigation("Motherboards");

                    b.Navigation("RAMs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountRTCoresEntity", b =>
                {
                    b.Navigation("GPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountRasterizationBlocksEntity", b =>
                {
                    b.Navigation("GPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountTensorCoresEntity", b =>
                {
                    b.Navigation("GPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountTexturerBlocksEntity", b =>
                {
                    b.Navigation("GPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUCountUniversalProcessorsEntity", b =>
                {
                    b.Navigation("GPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUEntity", b =>
                {
                    b.Navigation("VideoCards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.GPUs.GPUFrequencyEntity", b =>
                {
                    b.Navigation("GPUs");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.PCIEInterfaceEntity", b =>
                {
                    b.Navigation("Motherboards");

                    b.Navigation("VideoCards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCCapacityVideoMemoryEntity", b =>
                {
                    b.Navigation("VideoCards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCCountMonitorsEntity", b =>
                {
                    b.Navigation("VideoCards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCMemoryFrequencyEntity", b =>
                {
                    b.Navigation("VideoCards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCPriceEntity", b =>
                {
                    b.Navigation("VideoCards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VCThroughputCapacityEntity", b =>
                {
                    b.Navigation("VideoCards");
                });

            modelBuilder.Entity("DesktopDiplomProject.Server.Models.Entities.Components.VideoCards.VideoCardEntity", b =>
                {
                    b.Navigation("PCs");
                });
#pragma warning restore 612, 618
        }
    }
}
